spring:
  db:
    db1:
      url: jdbc:oracle:thin:@//<rds endpoint>:1521/demo
      username: admin
      password: admin
      driver-class-name: oracle.jdbc.driver.OracleDriver
      initialSize: 4
      maxTotal: 5
      maxIdle: 3
      minIdle: 1
    db2:
      url: jdbc:oracle:thin:@//<rds endpoint>:1521/demo
      username: admin
      password: admin
      driver-class-name: oracle.jdbc.driver.OracleDriver
      initialSize: 4
      maxTotal: 5
      maxIdle: 2
      minIdle: 1