spring:
  databases:
    db1:
      url: jdbc:oracle:thin:@//localhost:3306/db1
      username: user1
      password: password1
      driver-class-name: oracle.jdbc.OracleDriver
    db2:
      url: jdbc:oracle:thin:@//localhost:5432/db2
      username: user2
      password: password2
      driver-class-name: oracle.jdbc.OracleDriver